# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_headline', models.CharField(max_length=200)),
                ('day_date', models.DateTimeField()),
                ('date_updated', models.DateTimeField(verbose_name='Date updated')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heydayzdiary.Day'),
        ),
    ]
