# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0005_auto_20170830_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='heydayzdiary.Activity_type'),
            preserve_default=False,
        ),
    ]
