# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0007_auto_20170831_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('description', models.CharField(max_length=2000)),
                ('address', models.CharField(max_length=200)),
                ('phone_number_1', models.CharField(max_length=50)),
                ('phone_number_2', models.CharField(max_length=50)),
                ('email_1', models.CharField(max_length=100)),
                ('email_2', models.CharField(max_length=100)),
                ('website_1', models.CharField(max_length=200)),
                ('website_2', models.CharField(max_length=200)),
                ('social_media_1', models.CharField(max_length=200)),
                ('social_media_2', models.CharField(max_length=200)),
                ('social_media_3', models.CharField(max_length=200)),
                ('social_media_4', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
    ]
