# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0008_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_entry_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('day_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heydayzdiary.Day_entry')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heydayzdiary.Person')),
            ],
        ),
    ]
