# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0009_day_entry_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
