# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0012_auto_20170913_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_entry_person',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day_entry_person',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
