# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0013_auto_20170913_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
