# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0014_auto_20170919_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_entry',
            name='day_main_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
