# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0016_auto_20170919_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_entry',
            name='sleep_duration',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day_entry',
            name='sleep_quality',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
