# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0017_auto_20170919_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_entry',
            name='sleep_quality',
            field=models.IntegerField(blank=True),
        ),
    ]
