# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0019_auto_20170919_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_entry',
            name='sleep_duration',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
    ]
