# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0020_auto_20170919_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.CharField(max_length=500)),
                ('day_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heydayzdiary.Day_entry')),
            ],
        ),
        migrations.RenameModel(
            old_name='Activity_type',
            new_name='Exercise_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='day_entry',
        ),
        migrations.RenameField(
            model_name='exercise_type',
            old_name='activity_type_description',
            new_name='exercise_type_description',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heydayzdiary.Exercise_type'),
        ),
    ]
