# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0021_auto_20170920_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
