# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0025_auto_20170920_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.TimeField()),
                ('description', models.TextField(blank=True)),
                ('calories', models.IntegerField(blank=True)),
                ('day_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heydayzdiary.Day_entry')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heydayzdiary.Exercise_type')),
            ],
        ),
        migrations.CreateModel(
            name='Meal_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type_description', models.CharField(max_length=200)),
            ],
        ),
    ]
