# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0026_meal_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heydayzdiary.Meal_type'),
        ),
    ]
