# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0027_auto_20170920_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.TimeField()),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('day_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heydayzdiary.Day_entry')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heydayzdiary.Transaction_type'),
        ),
    ]
