# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0028_auto_20170920_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='study_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='heydayzdiary.Study_Subject'),
            preserve_default=False,
        ),
    ]
