# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0029_auto_20170921_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='heydayzdiary.Study_Subject'),
        ),
    ]
