# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0030_auto_20170921_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_entry',
            name='weather_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='day_entry',
            name='weather_rain',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day_entry',
            name='weather_sun',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day_entry',
            name='weather_temperature',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day_entry',
            name='weather_wind',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
