# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0031_auto_20170921_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_entry',
            name='bed_time',
            field=models.TimeField(blank=True, default="23:59"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day_entry',
            name='sleep_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='day_entry',
            name='wake_up_time',
            field=models.TimeField(blank=True, default="08:30"),
            preserve_default=False,
        ),
    ]
