# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0032_auto_20170921_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_entry',
            name='bed_time',
        ),
    ]
