# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0033_remove_day_entry_bed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='intensity',
            field=models.IntegerField(blank=True, default=5),
            preserve_default=False,
        ),
    ]
