# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0036_day_entry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_entry',
            name='wake_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
