# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0037_auto_20170921_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_entry',
            name='sleep_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day_entry',
            name='weather_rain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day_entry',
            name='weather_sun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day_entry',
            name='weather_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day_entry',
            name='weather_wind',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
