# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0038_auto_20170921_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
