# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0040_auto_20170922_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
