# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0041_auto_20170925_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode_of_travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='day_entry_location',
            name='travel_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day_entry_location',
            name='travel_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day_entry_location',
            name='mode_of_travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heydayzdiary.Mode_of_travel'),
        ),
    ]
