# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heydayzdiary', '0046_day_entry_is_template_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heydayzdiary.Job'),
        ),
    ]
